spring:
  application:
    name: comeya
  datasource:
    url: jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:6543/postgres?user=postgres.qelgsynddzpexyjghjqa&password=Pintura1!*@12
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        prepareThreshold: 0
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true


  jackson:
    time-zone: UTC
    default-property-inclusion: non_null

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: 918f69d918d2ffb791e12b3a3f193b1193429a5bac725cd2faffcf25f721a386
  expiration-ms: 86400000 # 24 horas

app:
  frontend-base-url: ${FRONTEND_BASE_URL:http://localhost:4200}
  password-reset:
    token-ttl-minutes: ${PASSWORD_RESET_TTL_MINUTES:15}

wompi:
  base-url: "https://sandbox.wompi.co/v1"
  public-key: "pub_test_A0guUdUKlpxDDPedplwYFjnHCepv3eCi"
  private-key: "prv_test_gvGkTcHjnnhmMqhGkD1hwCbr5FejBBWW"
  integrity-key: "test_integrity_js76z4Vt9GcjUPEuuRUV0qUU3XZoP8t6"
  webhook-secret: "test_events_VpWLpHMkSR2Nw4u0dxSaucRlnsiFtzql"

